apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cstor-csi-disk
  resources:
    requests:
      storage: 10Gi
