apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
  labels:
    k8s-app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: quay.io/prometheus/node-exporter:latest
          volumeMounts:
            - name: host-root
              mountPath: /host
              readOnly: true
      hostPID: true
      hostNetwork: true
      volumes:
        - name: host-root
          hostPath:
            path: /
            type: Directory
