apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-jiva-csi-default
  resources:
    requests:
      storage: 4Gi
