apiVersion: apps/v1
kind: Deployment
metadata:
  name: olama
  namespace: olama
spec:
  selector:
    matchLabels:
      name: olama
  template:
    metadata:
      labels:
        name: olama
    spec:
      containers:
      - name: olama
        image: ollama/ollama:latest
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
