apiVersion: v1
kind: Service
metadata:
  name: olama
  namespace: olama
spec:
  type: NodePort
  selector:
    name: olama
  ports:
  - port: 80
    name: http
    targetPort: http
    protocol: TCP
    nodePort: 30010
