apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: paperless
  namespace: paperless
  labels:
    app: paperless
spec:
  serviceName: paperless
  replicas: 3
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
    spec:
      containers:
        - name: paperless
          image: ghcr.io/paperless-ngx/paperless-ngx:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/mnt/openebs-csi/paperless/data"
              name: paperless-pvc
            - mountPath: "/mnt/openebs-csi/paperless/media"
              name: paperless-pvc
            - mountPath: "/mnt/openebs-csi/paperless/consume"
              name: paperless-pvc
          env:
            - name: PAPERLESS_REDIS
              value: "redis://redis:6379"
            - name: PAPERLESS_DATA_DIR
              value: "/mnt/openebs-csi/paperless/data"
            - name: PAPERLESS_MEDIA_ROOT
              value: "/mnt/openebs-csi/paperless/media"
            - name: PAPERLESS_CONSUMPTION_DIR
              value: "/mnt/openebs-csi/paperless/consume"
            - name: PAPERLESS_CONSUMER_POLLING
              value: "10"
            - name: PAPERLESS_ADMIN_USER
              value: "root"
            - name: PAPERLESS_ADMIN_PASSWORD
              value: "Kolotoc1234"
            - name: PAPERLESS_URL
              value: "https://paperless.homelab.org"
            - name: PAPERLESS_BIND_ADDR
              value: "0.0.0.0"
            - name: PAPERLESS_PORT
              value: "8000"

  volumeClaimTemplates:
    - metadata:
        name: paperless-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: cstor-csi-disk
        resources:
          requests:
            storage: 20Gi
