apiVersion: v1
kind: Service
metadata:
  name: paperless-nodeport
  namespace: paperless
  labels:
    app: paperless
spec:
  type: NodePort
  selector:
    app: paperless
  ports:
    - port: 8000
      targetPort: 8000

