apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"cstor-admission-webhook","openebs.io/component-name":"cstor-admission-webhook","openebs.io/version":"3.6.0"},"name":"openebs-cstor-admission-server","namespace":"openebs"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"cstor-admission-webhook"}},"strategy":{"rollingUpdate":null,"type":"Recreate"},"template":{"metadata":{"labels":{"app":"cstor-admission-webhook","openebs.io/component-name":"cstor-admission-webhook","openebs.io/version":"3.6.0"}},"spec":{"containers":[{"args":["-alsologtostderr","-v=2","2\u003e\u00261"],"env":[{"name":"OPENEBS_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"ADMISSION_WEBHOOK_NAME","value":"openebs-cstor-admission-server"},{"name":"ADMISSION_WEBHOOK_FAILURE_POLICY","value":"Fail"}],"image":"openebs/cstor-webhook:3.6.0","imagePullPolicy":"IfNotPresent","name":"admission-webhook"}],"serviceAccountName":"openebs-cstor-operator"}}}}
  creationTimestamp: "2025-03-14T08:46:54Z"
  generation: 2
  labels:
    app: cstor-admission-webhook
    openebs.io/component-name: cstor-admission-webhook
    openebs.io/version: 3.6.0
  name: openebs-cstor-admission-server
  namespace: openebs
  resourceVersion: "72151"
  uid: c8764589-6c60-473d-915b-ef0063203906
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cstor-admission-webhook
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-03-14T17:33:52+01:00"
      creationTimestamp: null
      labels:
        app: cstor-admission-webhook
        openebs.io/component-name: cstor-admission-webhook
        openebs.io/version: 3.6.0
    spec:
      containers:
      - args:
        - -alsologtostderr
        - -v=2
        - 2>&1
        env:
        - name: OPENEBS_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: ADMISSION_WEBHOOK_NAME
          value: openebs-cstor-admission-server
        - name: ADMISSION_WEBHOOK_FAILURE_POLICY
          value: Ignore
        image: openebs/cstor-webhook:3.6.0
        imagePullPolicy: IfNotPresent
        name: admission-webhook
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: openebs-cstor-operator
      serviceAccountName: openebs-cstor-operator
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-03-14T09:00:43Z"
    lastUpdateTime: "2025-03-14T16:35:20Z"
    message: ReplicaSet "openebs-cstor-admission-server-774fc47bd6" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-03-14T16:40:11Z"
    lastUpdateTime: "2025-03-14T16:40:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
