apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-operator
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
      - services
      - endpoints
      - nodes
    verbs: ["*"]
  - apiGroups:
      - "monitoring.coreos.com"
    resources:
      - prometheuses
      - prometheusrules
      - alertmanagers
      - servicemonitors
      - podmonitors
      - probes
      - thanosrulers
      - alertmanagerconfigs
      - scrapeconfigs
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups:
      - "monitoring.coreos.com"
    resources:
      - prometheusagents
      - prometheusagents/status
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources:
      - namespaces
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - statefulsets
    verbs: ["get", "list", "watch"]

