- name: Create app secret
  hosts: localhost
  tasks:
    - name: Create secret
      ansible.builtin.shell: |
        kubectl create secret tls "{{ app }}"-tls --key="{{ key_path }}" --cert="{{ crt_path }}" -n "{{ ns }}"
      changed_when: false
