apiVersion: v1
kind: Service
metadata:
  name: grafana-external
  labels:
    app: grafana-app
spec:
  type: NodePort
  selector:
    app: grafana-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30013
