apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
  name: cstor-disk-pool
  namespace: openebs
spec:
  pools:
  - dataRaidGroups:
    - blockDevices:
      - blockDeviceName: blockdevice-9baec796c5d9d263013fafbbb640bd8f
    nodeSelector:
      kubernetes.io/hostname: talos-1fa-atv
    poolConfig:
      dataRaidGroupType: stripe
  - dataRaidGroups:
    - blockDevices:
      - blockDeviceName: blockdevice-efdf68e2ef7b70f1ea3cb7317df12b4c
    nodeSelector:
      kubernetes.io/hostname: talos-92d-kv3
    poolConfig:
      dataRaidGroupType: stripe
  - dataRaidGroups:
    - blockDevices:
      - blockDeviceName: blockdevice-230d9cf1dd4287fc15e416d1b0bb32e2 
    nodeSelector:
      kubernetes.io/hostname: talos-25o-tzu
    poolConfig:
      dataRaidGroupType: stripe
