apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
  name: cstor-disk-pool
  namespace: openebs
spec:
  pools:
  - dataRaidGroups:
    - blockDevices:
      - blockDeviceName: blockdevice-43d3581a48f5efddbf810b0922376ea2
    nodeSelector:
      kubernetes.io/hostname: talos-lh1-dpg
    poolConfig:
      dataRaidGroupType: stripe
  - dataRaidGroups:
    - blockDevices:
      - blockDeviceName: blockdevice-eebbc8eaf74a21f5a5df619c5349dfa7
    nodeSelector:
      kubernetes.io/hostname: talos-3bv-so4
    poolConfig:
      dataRaidGroupType: stripe
  - dataRaidGroups:
    - blockDevices:
      - blockDeviceName: blockdevice-cc62019663dc274248d6bc3a66b90ec4 
    nodeSelector:
      kubernetes.io/hostname: talos-63w-tp7
    poolConfig:
      dataRaidGroupType: stripe
