apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
  name: cstor-disk-pool
  namespace: openebs
spec:
  pools:
  - dataRaidGroups:
    - blockDevices:
      - blockDeviceName: blockdevice-f7c0237838f28ffdd95a5bc48b9cb6d8
    nodeSelector:
      kubernetes.io/hostname: talos-1fa-atv
    poolConfig:
      dataRaidGroupType: stripe
  - dataRaidGroups:
    - blockDevices:
      - blockDeviceName: blockdevice-313a3c0d9de8db4a38c216f8d6c2bf9b
    nodeSelector:
      kubernetes.io/hostname: talos-92d-kv3
    poolConfig:
      dataRaidGroupType: stripe
  - dataRaidGroups:
    - blockDevices:
      - blockDeviceName: blockdevice-4e222a31ca4af425f0d74f13cdad8f8a
    nodeSelector:
      kubernetes.io/hostname: talos-25o-tzu
    poolConfig:
      dataRaidGroupType: stripe
