- name: VM Backup
  hosts: localhost
  vars_files:
    - secrets.yml
  tasks:
    - name: Backup all vms in the Proxmox cluster to storage mypbs
      community.general.proxmox_backup:
        api_user: "{{ apiuser }}"
        # api_token_id: "{{ ansibletokenid }}"
        # api_token_secret: "{{ ansibletokensecret }}"
        api_password: "{{ apiuserpassword }}"
        api_host: 172.16.0.2
        storage: local
        mode: all
