- name: VM Power Managment
  hosts: localhost
  vars_files:
    - secrets.yml
    # - vars.yaml
  tasks:
    - name: Start VMs
      community.general.proxmox_kvm:
        name: "{{ item.name }}"
        api_user: "{{ apiuser }}"
        api_password: "{{ apiuserpassword }}"
        # api_token_id: "{{ proxmox_token_id }}"
        # api_token_secret: "{{ proxmox_token_secret }}"
        api_host: 172.16.0.2
        state: stopped
        vmid: "{{ item.vmid }}"
        node: "{{ item.node }}"
      loop: "{{ kubeNodes }}"
