apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: linuxserver/radarr:latest
          env:
          - name: DB_TYPE
            value: "postgresql"
          - name: DB_HOST
            value: "172.16.0.99"
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: "radarr_db"
          - name: DB_USER
            value: "media"
          - name: DB_PASS
            value: "Kolotoc12345"
          ports:
            - containerPort: 7878
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: radarr-data
              mountPath: /Movies
            - name: qbtorrent-downloads
              mountPath: /config/Downloads
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: radarr-data
          persistentVolumeClaim:    
            claimName: radarr-data
        - name: qbtorrent-downloads
          persistentVolumeClaim:
            claimName: qbtorrent-config 
