apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: linuxserver/sonarr:latest
          env:
          - name: DB_TYPE
            value: "postgresql"
          - name: DB_HOST
            value: "172.16.0.99"
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: "sonarr_db"
          - name: DB_USER
            value: "media"
          - name: DB_PASS
            value: "Kolotoc12345"
          ports:
            - containerPort: 8989
          volumeMounts:
            - name: sonarr-config
              mountPath: "/config"
            - name: sonarr-data
              mountPath: "/TV Shows"
            - name: qbtorrent-downloads
              mountPath: /config/Downloads
      volumes:
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: sonarr-data
          persistentVolumeClaim:    
            claimName: sonarr-data
        - name: qbtorrent-downloads
          persistentVolumeClaim:
            claimName: qbtorrent-config
