apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-operator
rules:
  # Permissions for basic Kubernetes resources like ConfigMaps, Secrets, Services, Endpoints, Nodes
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
      - services
      - endpoints
      - nodes
      - pods
    verbs: ["*"]

  # Permissions for Prometheus Operator resources in the monitoring.coreos.com API group
  - apiGroups:
      - "monitoring.coreos.com"
    resources:
      - prometheuses
      - prometheusrules
      - alertmanagers
      - servicemonitors
      - podmonitors
      - probes
      - thanosrulers
      - alertmanagerconfigs
      - scrapeconfigs
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Permissions for Prometheus Agents and Prometheus Agent Status
  - apiGroups:
      - "monitoring.coreos.com"
    resources:
      - prometheusagents
      - prometheusagents/status
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Permissions for namespaces
  - apiGroups: [""]
    resources:
      - namespaces
    verbs: ["get", "list", "watch"]

  # Permissions for StatefulSets (Add creation and deletion verbs)
  - apiGroups: ["apps"]
    resources:
      - statefulsets
    verbs: ["create", "get", "list", "watch", "update", "delete"]

  # Permissions for Prometheus Server specific resources (optional)
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - prometheuses/status
    verbs: ["get", "update"]
