apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mediastack
  namespace: media
  labels:
    app: mediastack
spec:
  serviceName: mediastack
  replicas: 3
  selector:
    matchLabels:
      app: mediastack
  template:
    metadata:
      labels:
        app: mediastack
    spec:
      containers:
        - name: prowlarr
          image: linuxserver/prowlarr:latest
          ports:
            - containerPort: 9696
          volumeMounts:
            - name: prowlarr-pvc
              mountPath: /config
              subPath: prowlarr
        - name: radarr
          image: linuxserver/radarr:latest
          env:
          - name: DB_TYPE
            value: "postgresql"
          - name: DB_HOST
            value: "172.29.3.211"
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: "radarr_db"
          - name: DB_USER
            value: "media"
          - name: DB_PASS
            value: "Kolotoc12345"
          ports:
            - containerPort: 7878
          volumeMounts:
            - name: radarr-pvc
              mountPath: /config
              subPath: radarr
            - name: media-pvc
              mountPath: /Movies
            - name: media-pvc
              mountPath: /Downloads
        - name: sonarr
          image: linuxserver/sonarr:latest
          env:
          - name: DB_TYPE
            value: "postgresql"
          - name: DB_HOST
            value: "172.29.3.211"
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: "sonarr_db"
          - name: DB_USER
            value: "media"
          - name: DB_PASS
            value: "Kolotoc12345"
          ports:
            - containerPort: 8989
          volumeMounts:
            - name: sonarr-pvc
              mountPath: "/config"
              subPath: sonarr
            - name: media-pvc
              mountPath: "/TV Shows"
            - name: media-pvc
              mountPath: /Downloads
        - name: qbtorrent
          image: linuxserver/qbittorrent:latest
          envFrom:
            - configMapRef:
                name: qbtorrent-configmap
          ports:
            - containerPort: 8080
              name: web-ui
              protocol: TCP
            - containerPort: 6881
              name: torrent-tcp
              protocol: TCP
            - containerPort: 6881
              name: torrent-udp
              protocol: UDP
          volumeMounts:
            - name: qbittorrent-pvc
              mountPath: /config
              subPath: qbittorent
            - name: media-pvc
              mountPath: /Movies
            - name: media-pvc
              mountPath: "/TV Shows"

  volumeClaimTemplates:
    - metadata:
        name: media-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: cstor-csi-disk
        resources:
          requests:
            storage: 100Gi

    - metadata:
        name: prowlarr-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: cstor-csi-disk
        resources:
          requests:
            storage: 10Gi

    - metadata:
        name: radarr-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: cstor-csi-disk
        resources:
          requests:
            storage: 10Gi

    - metadata:
        name: sonarr-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: cstor-csi-disk
        resources:
          requests:
            storage: 10Gi

    - metadata:
        name: qbittorrent-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: cstor-csi-disk
        resources:
          requests:
            storage: 10Gi
