apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-csi
  namespace: ceph-csi
data:
  ceph.conf: |-
    [global]
    auth_cluster_required = cephx
    auth_service_required = cephx
    auth_client_required = cephx
  keying: |
metadata:
  name: ceph-config
  namespace: ceph-csi
