apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ceph-csi
stringData:
  userID: admin
  userKey: AQAfiENnUCZjLxAAyY6b5qV3sfbtvb4pwfDzOQ==
  adminID: admin
  adminKey: AQAfiENnUCZjLxAAyY6b5qV3sfbtvb4pwfDzOQ==
